Testing `test/e2e/alcotest/failing/check_located.ml'.
This run has ID `<uuid>'.

ASSERT Expected failure
  [FAIL]    check › here
ASSERT Expected failure
  [FAIL]    check › pos
ASSERT Expected failure
  [FAIL]    check_raises › here
ASSERT Expected failure
  [FAIL]    check_raises › pos
ASSERT Expected failure
  [FAIL]    fail › here
ASSERT Expected failure
  [FAIL]    fail › pos

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    check › here                                                       │
└──────────────────────────────────────────────────────────────────────────────┘
File "test/e2e/alcotest/failing/check_located.ml", line 2, character 30:
FAIL Expected failure

   Expected: `true'
   Received: `false'

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    check › pos                                                        │
└──────────────────────────────────────────────────────────────────────────────┘
File "test/e2e/alcotest/failing/check_located.ml", line 4, character 10:
FAIL Expected failure

   Expected: `true'
   Received: `false'

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    check_raises › here                                                │
└──────────────────────────────────────────────────────────────────────────────┘
File "test/e2e/alcotest/failing/check_located.ml", line 2, character 30:
FAIL Expected failure: expecting Failure(""), got nothing.
 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    check_raises › pos                                                 │
└──────────────────────────────────────────────────────────────────────────────┘
File "test/e2e/alcotest/failing/check_located.ml", line 4, character 10:
FAIL Expected failure: expecting Failure(""), got nothing.
 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    fail › here                                                        │
└──────────────────────────────────────────────────────────────────────────────┘
File "test/e2e/alcotest/failing/check_located.ml", line 2, character 30:
FAIL Expected failure
 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]    fail › pos                                                         │
└──────────────────────────────────────────────────────────────────────────────┘
File "test/e2e/alcotest/failing/check_located.ml", line 4, character 10:
FAIL Expected failure
 ──────────────────────────────────────────────────────────────────────────────

6 failures! in <test-duration>s. 6 tests run.
